[tox]
isolated_build = True

[testenv:type]
skipsdist = true
skip_install = true
deps =
    mypy
commands =
    mypy --install-types --non-interactive {posargs:.}

[testenv:format]
skipsdist = true
skip_install = true
deps =
    black
    isort
commands =
    black {posargs:.}
    isort {posargs:.}

[testenv:buildcli]
deps =
    pyinstaller
commands =
    # --collect-data bundles kobodl/templates, without which `kobodl serve` cannot render any page
    pyinstaller --onefile --collect-data kobodl kobodl/__main__.py {posargs}
