
name: Pyinstaller Build

on:
  release:
    types: [created]

jobs:

  pyinstaller:
    name: Build for multiple platforms
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
        python-version: [3.8]

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Install tox
        run: |
          python -m pip install --upgrade pip;
          pip install tox;
      -
        run: tox -e buildcli -- --name kobodl-${{ matrix.python-version }}
      - 
        name: Upload Release Asset
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist/kobodl*"]'
