name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to PyPI ✨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - run: pip install poetry twine
      - run: poetry install
      - run: poetry build
      - run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

  pyinstaller:
    name: Build for multiple platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        python-version: [3.8]
        include:
          -
            os: windows-latest
            name: windows
          -
            os: macos-latest
            name: macos
          -
            os: ubuntu-latest
            name: ubuntu

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Install tox
        run: |
          python -m pip install --upgrade pip;
          pip install tox;
      -
        run: tox -e buildcli -- --name kobodl-${{ matrix.name }}
      - 
        name: Upload Release Asset
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist/kobodl*"]'
